const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const html=fs.readFileSync(require('path').join(__dirname,'..','index.html'),'utf8');
const elements={};const el=id=>elements[id]??=( {value:'',textContent:'',innerHTML:'',disabled:false,classList:{toggle(){}},options:[{text:'test'}],selectedIndex:0});
const context={document:{querySelector:s=>el(s),querySelectorAll:()=>[]},window:{addEventListener(){}},console:{info(){},error(){},warn(){}},localStorage:{setItem(){},getItem(){return null},removeItem(){}},URLSearchParams,performance, setTimeout, clearTimeout,alert(){},confirm:()=>false,fetch:()=>{throw Error('Unexpected network')}};vm.createContext(context);vm.runInContext(require('./helpers/frontend.cjs').loadSource(),context);
const run=s=>vm.runInContext(s,context);
(async()=>{
run('makeRows([{id:1,title:"Song",artist:"Artist",genre:"Pop",tags:[7]}]);rows[0].fields={Genre:"current",Artist:"current"};rows[0].genreTags=[];rows[0].tagMode="replace"');
run('window.setPageOverride("Genre","Dancehall");window.setPageOverride("Artist","New Artist");window.setPageOverride("CustomTags","Dancehall, Party, party");window.togglePageOverride(1,true)');
assert.equal(run('finalValue(rows[0],"Genre")'),'Dancehall');
assert.equal(run('chosenValue(rows[0],"Artist")'),'New Artist');
assert.equal(run('effectiveTags(rows[0]).length'),2);
assert.equal(run('effectiveTagMode(rows[0])'),'add');
run('window.togglePageOverride(1,false)');
assert.equal(run('chosenValue(rows[0],"Artist")'),'Artist');
assert.equal(run('effectiveTagMode(rows[0])'),'replace');
run('window.togglePageOverride(1,true);window.setPageOverride("Year","bad")');
assert.equal(run('invalidManual(rows[0])'),true);
run('window.setPageOverride("Year","1999");rows[0].decision="accepted"');
assert.ok(run('reviewedCSV()').includes('Dancehall'));
run('async function api(){return {data:{track:{id:1,tags:[7,8]}}}};async function ensureTag(label){return {id:label==="Dancehall"?7:9}};async function patchTrack(id,patch){globalThis.sent=patch}');
await run('applyOne(rows[0])');
assert.deepEqual(JSON.parse(run('JSON.stringify(sent.tags)')),[7,8,9]);
assert.equal(run('sent.genre'),'Dancehall');assert.equal(run('sent.year'),1999);
run('window.setPageOverride("Genre","House")');
assert.equal(run('finalValue(rows[0],"Genre")'),'Dancehall');
run('makeRows([{id:2,title:"Song",artist:"Artist",tags:[8]}]);rows[0].fields={};rows[0].genreTags=[];state.allTags=[{id:7,label:"hiphop",categoryId:1},{id:8,label:"Hiphop",categoryId:2}];state.pageOverrides={CustomTags:"hiphop, HIPHOP"};rows[0].usePageOverrides=true;api=async()=>({data:{track:{id:2,tags:[8]}}});ensureTag=async()=>{throw Error("Must reuse assigned tag")};');
await run('applyOne(rows[0])');
assert.deepEqual(JSON.parse(run('JSON.stringify(sent.tags)')),[8]);
run('makeRows([{id:3,title:"Song",artist:"Artist",genre:"",tags:[8]}]);rows[0].fields={};rows[0].genreTags=["Old selection"];state.pageOverrides={CustomTags:"New",OverwriteTags:true};rows[0].usePageOverrides=true;api=async()=>({data:{track:{id:3,tags:[8]}}});ensureTag=async()=>({id:9});');
assert.equal(run('effectiveTagMode(rows[0])'),'replace');
assert.deepEqual(JSON.parse(run('JSON.stringify(effectiveTags(rows[0]))')),['New']);
await run('applyOne(rows[0])');
assert.deepEqual(JSON.parse(run('JSON.stringify(sent.tags)')),[9]);
console.log('PASS: Page overrides preserve choices, validate numbers, export final values, add unique tags and freeze applied results.');
})().catch(e=>{console.error(e);process.exit(1)});
