const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const html=fs.readFileSync(require('path').join(__dirname,'..','index.html'),'utf8');
const elements={};const el=id=>elements[id]??=( {value:'',textContent:'',innerHTML:'',disabled:false,classList:{toggle(){}},options:[{text:'test'}],selectedIndex:0});
const context={document:{querySelector:s=>el(s),querySelectorAll:()=>[]},window:{addEventListener(){}},console:{info(){},error(){},warn(){}},localStorage:{setItem(){},getItem(){return null},removeItem(){}},URLSearchParams,performance, setTimeout, clearTimeout,alert(){},confirm:()=>false,fetch:()=>{throw Error('Unexpected network')}};vm.createContext(context);vm.runInContext(html.match(/<script>([\s\S]*?)<\/script>/)[1],context);
const run=s=>vm.runInContext(s,context);
(async()=>{
context.document.querySelector=s=>{const x=el(s);x.querySelector=()=>null;return x};
run('tagDefaults={tagMode:"replace",includeMix:true};makeRows([{id:1,title:"Song (Clean Extended Intro)",genre:"Soul",tags:[]}]);window.setAdvanced(true);rows[0].result={strGenre:"Pop",intTrackNumber:"3"};initChoices(rows[0])');
assert.equal(run('rows[0].tagMode'),'replace');
assert.equal(run('includedMixTags(rows[0]).join(",")'),'Clean,Extended,Intro');
run('window.setManual(1,"Genre","Jazz")');assert.equal(run('rows[0].fields.Genre'),'manual');assert.equal(run('rows[0].mainGenre'),'Jazz');assert.equal(elements['#final-1-Genre'].textContent,'Jazz');
run('window.fieldChoice(1,"Genre","current")');assert.equal(run('rows[0].mainGenre'),'Soul');
run('window.fieldChoice(1,"Genre","api")');assert.equal(run('rows[0].mainGenre'),'Pop');
assert.match(run('reviewHTML(rows[0])'),/Final output/);assert.match(run('reviewHTML(rows[0])'),/source-value active/);
run('window.setManual(1,"Year","oops")');assert.equal(run('invalidManual(rows[0])'),true);
run('window.fieldChoice(1,"Year","current");rows[0].genreTags=["Pop"];tagCategories=[{id:4,label:"Mix"}];allTags=[];async function api(){return {data:{track:{id:1,tags:[99]}}}};async function refreshTags(){};async function ensureTag(label,categoryId){(globalThis.created??=[]).push({label,categoryId});return {id:{Pop:1,Clean:2,Extended:3,Intro:4}[label]}};async function patchTrack(id,p){globalThis.sent=p}');
await run('applyOne(rows[0])');assert.equal(run('sent.tags.join(",")'),'1,2,3,4');assert.equal(run('created.filter(x=>x.categoryId===4).length'),3);
run('rows[0].applied=false;window.setIncludeMix(1,false)');await run('applyOne(rows[0])');assert.equal(run('sent.tags.join(",")'),'1');
run('window.setTagMode(1,"add")');assert.equal(run('includedMixTags(rows[0]).length'),0);
assert.equal(run('detectedMixTags({original:{Title:"Unclean extendedness"}}).length'),0);
assert.equal(run('detectedMixTags({original:{Title:"Song (Acapella-In)"}}).join(",")'),'Acapella-In');
run('rows[0].applied=false;window.setManual(1,"Genre","Jazz");window.allGenreTags(1,false)');
assert.equal(run('effectiveTags(rows[0]).join(",")'),'Jazz');assert.equal(elements['#main-genre-1'].textContent,'Jazz');
assert.ok(!run('tagHTML(rows[0])').includes('onchange="setMainGenre'));
run('window.setTagMode(1,"replace");window.setIncludeMix(1,false)');assert.equal(run('effectiveTags(rows[0]).join(",")'),'Jazz');
run('window.setManual(1,"Genre","")');assert.equal(run('effectiveTags(rows[0]).length'),0);
elements['#settingsDialog']={showModal(){},close(){this.closed=true}};
run('async function localMetadata(){return {advanced_mode:true,overwrite_custom_tags:false,include_mix_tags_from_title:true,sonovault_configured:true,audiodb_configured:true,show_debug_log:true,theme:"system",config_storage:"env"}}');
await run('window.openSettings()');assert.equal(elements['#settingsAdvanced'].checked,true);
assert.equal(elements['#settingsSono'].placeholder,'********');assert.equal(elements['#settingsSono'].value,'');assert.equal(elements['#settingsDebug'].checked,true);
elements['#settingsSono'].value='';elements['#settingsOverwrite'].checked=true;
context.confirm=()=>false;context.fetch=()=>{throw Error('Cancelled save must not send a request')};await run('window.saveSettings()');assert.equal(elements['#settingsDialog'].closed,undefined);
context.fetch=async(url,options)=>{const body=JSON.parse(options.body);assert.ok(!Object.hasOwn(body,'sonovault_api_key'));assert.equal(body.overwrite_custom_tags,true);assert.equal(body.show_debug_log,true);return {ok:true,json:async()=>({...body,sonovault_configured:true})}};
context.confirm=()=>true;await run('window.saveSettings()');assert.equal(run('tagDefaults.tagMode'),'replace');assert.equal(elements['#settingsDialog'].closed,true);
console.log('PASS: configured defaults, title markers, Mix-category writes, toggle exclusion, automatic Typed selection, genre synchronization and final preview. No live writes.');
})().catch(e=>{console.error(e);process.exit(1)});
