const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const html=fs.readFileSync(require('path').join(__dirname,'..','index.html'),'utf8');
const elements={};const el=id=>elements[id]??=( {value:'',textContent:'',innerHTML:'',disabled:false,classList:{toggle(){}},options:[{text:'test'}],selectedIndex:0});
const context={document:{querySelector:s=>el(s),querySelectorAll:()=>[]},window:{addEventListener(){}},console:{info(){},error(){},warn(){}},localStorage:{setItem(){},getItem(){return null},removeItem(){}},URLSearchParams,performance, setTimeout, clearTimeout,alert(){},confirm:()=>false,fetch:()=>{throw Error('Unexpected network')}};vm.createContext(context);vm.runInContext(require('./helpers/frontend.cjs').loadSource(),context);
const run=s=>vm.runInContext(s,context);
(async()=>{
run('async function api(path){return {data:{track:{id:Number(path.split("=")[1]),tags:[]}}}};async function ensureTag(){return {id:101}}');
run("window.setAdvanced(true)");
const direct={idTrack:'12345',strTrack:'Crazy in Love',strArtist:'Beyoncé',strAlbum:'Dangerously in Love',strGenre:'R&B',intYearReleased:'2003'};
context.direct=direct;
run('makeRows([{id:1,title:"Crazy in Love",artist:"Beyoncé",genre:"Pop"},{id:2,title:"Crazy in Love (Instrumental)",artist:"Beyonce",albumTitle:"",genre:"Pop",year:0,tags:[]}]);rows[0].result=commonResult("audiodb",direct,"Beyoncé","Crazy in Love");initChoices(rows[0]);rows[1].error="No match";attachRecord(rows[1],sourceRecords.get("audiodb:12345"))');
assert.equal(run('rows[0].result._recordId'),'12345');assert.equal(run('sourceRecords.size'),1);
assert.equal(run('rows[1].result'),null);assert.equal(run('hasProposal(rows[1])'),true);
assert.equal(run('Object.values(rows[1].fields).every(v=>v==="current")'),true);
assert.equal(run('selectedTags(rows[1]).length'),0);
assert.match(run('reviewHTML(rows[1])'),/TheAudioDB · ID 12345/);
assert.match(run('reviewHTML(rows[1])'),/data-choice="record"/);
run('window.fieldChoice(2,"Title","record")');assert.equal(run('rows[1].fields.Title'),'current');
run('window.fieldChoice(2,"Year","record");window.fieldChoice(2,"AlbumTitle","record");window.decide(2,"accepted")');
assert.equal(run('rows[1].decision'),'accepted');assert.equal(run('bulkEligible(rows[1])'),false);
assert.equal(elements['#exportBtn'].disabled,false);
const csv=run('parseCSV(reviewedCSV())');assert.equal(csv[1][1],'Crazy in Love (Instrumental)');assert.equal(csv[1][3],'Dangerously in Love');assert.equal(csv[1][4],'Pop');assert.equal(csv[1][5],'2003');
run('async function patchTrack(id,p){globalThis.sent={id,patch:p}}');await run('applyOne(rows[1])');
assert.deepEqual(JSON.parse(run('JSON.stringify(sent)')),{id:2,patch:{albumTitle:'Dangerously in Love',year:2003,tags:[101]}});
assert.equal(run('rows[0].decision'),'pending');assert.equal(run('rows[0].result.strAlbum'),'Dangerously in Love');
run('rows[1].applied=false;window.clearRecord(2)');assert.equal(run('rows[1].reference'),null);assert.equal(run('rows[1].fields.Year'),'current');assert.equal(run('rows[1].decision'),'pending');
run('commonResult("sonovault",{id:12345,title:"Different",artists:[{name:"Other"}]},"Other","Different")');assert.equal(run('sourceRecords.size'),2);
run('registerRecord({_source:"Sonovault",strTrack:"Missing ID"},"sonovault",null)');assert.equal(run('sourceRecords.size'),2);
assert.equal((await run('fetchRecordById("audiodb","12345")')).strTrack,'Crazy in Love');
await assert.rejects(run('fetchRecordById("audiodb","../12345")'),/numeric track ID/);
let called;context.AbortSignal=AbortSignal;context.fetch=async(url)=>{called=url;return {ok:true,json:async()=>({payload:{track:[{...direct,idTrack:'777'}]},cached:false})}};
assert.equal((await run('fetchRecordById("audiodb","777")'))._recordId,'777');assert.match(called,/audiodb\/record\?id=777$/);
context.fetch=async()=>({ok:true,json:async()=>({payload:{track:[{...direct,idTrack:'wrong'}]}})});await assert.rejects(run('fetchRecordById("audiodb","999")'),/requested track ID/);
context.fetch=async(url)=>{called=url;return {ok:true,json:async()=>({payload:{data:{id:'888',title:'Test',artists:[{name:'Example'}]}}})}};
assert.equal((await run('fetchRecordById("sonovault","888")'))._recordId,'888');assert.equal(called,'/metadata/sonovault/record?id=888');
console.log('PASS: record IDs, provider namespaces, shared-record reuse on an unmatched version, safe defaults, protected title, per-field CSV/write payload, source independence, clearing record, cached ID lookup, both provider endpoints and mismatched-ID rejection.');
})().catch(e=>{console.error(e);process.exit(1)});
